version: "3"
services:
  backend:
    container_name: stockpos-backend
    image: ${REPO}:${STOCKPOS_BACKEND_TAG:-latest}
    restart: always
    # depends_on:
    #   - db
    environment:
      MysqlDbSettings:Host: ${DB_SERVER_URL}
      MysqlDbSettings:User: ${DB_USERNAME}
      MysqlDbSettings:Password: ${DB_PASSWORD}
    ports:
      - 80:80
    networks:
      - multi
  # db:
  #   image: mysql:8.0.31
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: 'stockpos'
  #     # So you don't have to use root, but you can if you like
  #     MYSQL_USER: 'admin'
  #     # You can use whatever password you like
  #     MYSQL_PASSWORD: {{DB_PASSWORD}}
  #     # Password for root access
  #     MYSQL_RANDOM_ROOT_PASSWORD: yes
  #   ports:
  #     # <Port exposed> : < MySQL Port running inside container>
  #     - 3306:3306
  #   expose:
  #     # Opens port 3306 on the container
  #     - 3306
  #     # Where our data will be persisted
  #   volumes:
  #     - my-db:/var/lib/mysql
  #   networks:
  #     - multi

# # Names our volume
# volumes:
#   my-db:

networks:
  multi:
